name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/alephdata/projects/10
          github-token: ${{ secrets.ALEPH_GITHUB_TOKEN }}
 # label_issues:
    # name: Add repo label for clarity
    # runs-on: ubuntu-latest
    # permissions:
      # issues: write
    # steps:
      # - name: Label issues
        # uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        # with:
          # add-labels: "FtM"
          # repo-token: ${{ secrets.ALEPH_GITHUB_TOKEN }}
